apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 1ce7f682f49639f502c98fb8361bf476a9262bba45f8b8484cee1b2cf7c0f5dd
    cni.projectcalico.org/podIP: 192.168.0.15/32
    cni.projectcalico.org/podIPs: 192.168.0.15/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.15"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.15"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-03-04T06:20:32Z"
  generateName: katafygio-78ddcb7d98-
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 78ddcb7d98
    release: katafygio
  name: katafygio-78ddcb7d98-nzzsg
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: katafygio-78ddcb7d98
    uid: fbc29494-b663-4fee-9bde-f311198b30ca
spec:
  containers:
  - args:
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/mutate:applabel1
    imagePullPolicy: Always
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/katafygio
      name: katafygio-data
    - mountPath: /etc/katafygio
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xczvt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsUser: 65534
  serviceAccount: katafygio
  serviceAccountName: katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: katafygio-data
    persistentVolumeClaim:
      claimName: katafygio
  - configMap:
      defaultMode: 420
      name: katafygio-config
    name: config-volume
  - name: kube-api-access-xczvt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
